# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='strainCurrent',
            field=models.IntegerField(default=1),
        ),
    ]
