# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0002_character_straincurrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='scoordination',
            new_name='coordination',
        ),
    ]
